CREATE TABLE user_roles (
id INT UNSIGNED AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
created_by INT UNSIGNED DEFAULT 1,
updated_by INT UNSIGNED DEFAULT 1,
PRIMARY KEY (id),
CONSTRAINT uk_user_roles_name UNIQUE (name)
);

-- Insert table data
INSERT INTO user_roles (name)
VALUES ('Admin'), ('Instructor'),('Student');
